### ISSUE TITLE
代码训练

### ISSUE THREAD

**Issue by unrealMJ** [Haochen-Wang409/U2PL#54]
您好，感谢您的工作，我在使用您的代码时遇到一些问题，希望能够得到您的帮助。
我使用了4张2080Ti，我做了如下修改，backbone修改为原始的res50并load预训练的权重，batch修改为1，lr修改为0.00025.
但是训练结果很奇怪，看上去第一轮只用有标注数据是没问题的，但是后面的半监督方法就不work了
![image](https://user-images.githubusercontent.com/45420156/173972086-2be2a7bf-3973-4b4f-9a8f-915aac75000f.png)

训练过程中的loss也没有下降
![image](https://user-images.githubusercontent.com/45420156/173972265-642e373b-909e-42d5-b56b-ed65afab735a.png)
![image](https://user-images.githubusercontent.com/45420156/173972278-fa29cc79-818a-4abc-ad4a-273d9ecf9042.png)
![image](https://user-images.githubusercontent.com/45420156/173972300-6087903e-77c8-447b-9df4-30b21f6036e3.png)

下面是我修改后的config文件，希望能够得到您的帮助，非常感谢

``` yaml
dataset: # Required.
  type: pascal_semi
  train:
    data_root: ../../../../data/VOC2012
    data_list: ../../../../data/splits/pascal/1464/labeled.txt
    flip: True
    GaussianBlur: False
    rand_resize: [0.5, 2.0]
    #rand_rotation: [-10.0, 10.0]
    crop:
      type: rand
      size: [513, 513] # crop image with HxW size
  val:
    data_root: ../../../../data/VOC2012
    data_list: ../../../../data/splits/pascal/val.txt
    crop:
      type: center
      size: [513, 513] # crop image with HxW size
  batch_size: 1
  n_sup: 1464
  noise_std: 0.1
  workers: 2
  mean: [123.675, 116.28, 103.53]
  std: [58.395, 57.12, 57.375]
  ignore_label: 255

trainer: # Required.
  epochs: 80
  eval_on: True
  optimizer:
    type: SGD
    kwargs:
      lr: 0.00025  # 4GPUs
      momentum: 0.9
      weight_decay: 0.0001
  lr_scheduler:
    mode: poly
    kwargs:
      power: 0.9
  unsupervised:
    TTA: False
    drop_percent: 80
    apply_aug: cutmix
  contrastive:
    negative_high_entropy: True
    low_rank: 3
    high_rank: 20
    current_class_threshold: 0.3
    current_class_negative_threshold: 1
    unsupervised_entropy_ignore: 80
    low_entropy_threshold: 20
    num_negatives: 50
    num_queries: 256
    temperature: 0.5

saver:
  snapshot_dir: checkpoints
  pretrain: ''

criterion:
  type: CELoss
  kwargs:
    use_weight: False

net: # Required.
  num_classes: 21
  sync_bn: True
  ema_decay: 0.99
  encoder:
    type: u2pl.models.resnet.resnet50
    kwargs:
      multi_grid: True
      zero_init_residual: True
      fpn: True
      replace_stride_with_dilation: [False, True, True]  #layer0...1 is fixed, layer2...4
  decoder:
    type: u2pl.models.decoder.dec_deeplabv3_plus
    kwargs:
      inner_planes: 256
      dilations: [12, 24, 36]

```
