### ISSUE TITLE
About ablation study in paper

### ISSUE THREAD

**Issue by DISAPPEARED13** [Haochen-Wang409/U2PL#73]
Hi there! 
I notice that your team use "Plain L_c" for one of the contrast learning experiment. And at Fig.4 volumn4 AKA (d) means

> The vanilla contrastive learning framework, where all pixels are used as negative samples without entropy filtering.

Could you please tell me that which kind of contrast learning framework used? Or just change the training process while you finished this experiment?

Thanks a lot!

**Comment by Haochen-Wang409** [comment]
You could add ```negative_high_entropy: False``` to ```config.yaml``` for conducting vanilla contrastive learning experiments.

For instance:
```
  contrastive:
    negative_high_entropy: True
    low_rank: 3
    high_rank: 20
    current_class_threshold: 0.3
    current_class_negative_threshold: 1
    unsupervised_entropy_ignore: 80
    low_entropy_threshold: 20
    num_negatives: 50
    num_queries: 256
    temperature: 0.5
    negative_high_entropy: False
```
